(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Begin["ClojurianScopes`"];


Needs["FunctionalExtras`"];


SetAttributes[ClojurianScopes`Function, HoldAllComplete]


ClojurianScopes`Function[bindings_, body__] := Function[bindings, CompoundExpression[body]];


ClojurianScopes`Function[body__] := Function[CompoundExpression[body]];


SetAttributes[ClojurianScopes`Let, HoldAllComplete]


ClojurianScopes`Let[bindings_, body__] :=
Let[bindings, CompoundExpression[body]]


SetAttributes[ClojurianScopes`With, HoldAllComplete]


ClojurianScopes`With[bindings_, body__] :=
With[bindings, CompoundExpression[body]]


SetAttributes[ClojurianScopes`Block, HoldAllComplete]


ClojurianScopes`Block[bindings_, body__] :=
Block[bindings, CompoundExpression[body]]


SetAttributes[ClojurianScopes`Module, HoldAllComplete]


ClojurianScopes`Module[bindings_, body__] :=
Module[bindings, CompoundExpression[body]]


End[];
